version: '3.8'

services:
  cleanup:
    image: busybox
    container_name: cleanup
    command: sh -c "docker stop pramaan && docker rm pramaan || true"
    depends_on:
      - proxy  # Or the services that should run first

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - server
      - server2
    restart: 'unless-stopped'

  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3004:3004'
    volumes:
      - ./:/home/ubuntu/github_repos/pramaan
      - node_modules:/home/ubuntu/github_repos/pramaan/node_modules
    networks:
      - backend
    restart: 'unless-stopped'

  server2:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server2
    ports:
      - '3005:3004'
    volumes:
      - ./:/home/ubuntu/github_repos/pramaan
      - node_modules:/home/ubuntu/github_repos/pramaan/node_modules
    networks:
      - backend
    restart: 'unless-stopped'

networks:
  backend:
    driver: bridge

volumes:
  node_modules:
    driver: local
